ALTER TABLE "locations" ADD COLUMN "zone" TEXT NOT NULL DEFAULT '';
ALTER TABLE "locations" ADD COLUMN "aisle" TEXT NOT NULL DEFAULT '';
ALTER TABLE "locations" ADD COLUMN "rack" TEXT NOT NULL DEFAULT '';
ALTER TABLE "locations" ADD COLUMN "level" TEXT NOT NULL DEFAULT '';
ALTER TABLE "locations" ADD COLUMN "position" TEXT NOT NULL DEFAULT '';
ALTER TABLE "locations" ADD COLUMN "kind" TEXT NOT NULL DEFAULT 'STORAGE';
